export const education = [
  {
    id: 1,
    title: "IT School GoIT",
    data: "2024 - now",
    name: "Fullstack Developer",
    text: "Improved clean code practices and gained team experience as both a developer and team lead. Learned to build back-end services and manage full-stack project development.",
  },
  {
    id: 2,
    title: "IT courses by Okten School",
    data: "2023",
    name: "Frontend Developer",
    text: "Strengthened programming fundamentals by building a pet project and working with Figma for UI design. Gained practical experience in front-end workflows and independent problem-solving.",
  },
  {
    id: 3,
    title: "Ostrogradskyi National University of Kremenchuk",
    data: "2013 - 2018",
    name: "Computer Science, Master's Degree",
    text: "Gained foundational knowledge in programming, computer logic, and design principles during university studies, while also developing critical thinking and problem-solving skills.",
  },
];

export const experience = [
  {
    id: 1,
    title: "Security Police",
    data: "2017 - 2021",
    name: "Technical security engineer",
    text: "Learned to set priorities and adapt to different work styles while delivering reliable results. Gained experience in communication, task management, and supporting overall work efficiency.",
  },
];

export const projects = [
  {
    id: 1,
    title: "Landing - 'Portfolio'",
    data: "2025",
    skills: ["#js", "#html", "#css"],
    url: "https://dimabarbara.github.io/project-WebGuru/",
    foto: "./projects/full-stack.png",
    alt: "Portfolio",
    text: "Portfolio site. Role: Developer. Collaborated on the 'About Us' section as part of a pair programming effort. Conducted thorough code reviews to ensure consistency and quality, assisted in the development of other sections, and actively participated in debugging and optimization code and images tasks to improve site performance.",
  },
  {
    id: 2,
    title: "Landing - 'Watcharm'",
    data: "2024",
    skills: ["#html", "#css"],
    url: "https://maskaa22.github.io/perfect-developers/",
    foto: "./projects/watcharm.png",
    alt: "Watcharm",
    text: "A responsive website built with attention to layout and performance. Role: Team Lead & Developer. Responsible for project setup on GitHub, checking build errors, monitoring live page performance, and developing the header component. Also contributed to team coordination, code reviews, and deployment process.",
  },
  {
    id: 3,
    title: "Website - 'Olena Studio'",
    data: "2023",
    skills: ["#react", "#node", "#redux", "#mongo", "#chart"],
    url: "https://o-react.vercel.app/",
    foto: "./projects/olena-studio.png",
    alt: "Olena Studio",
    text: "Full stack website. Logining, salon appointment, products buy, etc. Separate admin account with setting products and more. Also, the site has an analysis for the administrator using React Chart. The documentation is written by Swagger.",
  },
  {
    id: 4,
    title: "Website - 'Ulia Ushenko'",
    data: "2023",
    skills: ["#react", "#node", "#redux", "#mongo"],
    url: "https://ulia-ushenko.vercel.app/",
    foto: "./projects/ulia-ushenko.png",
    alt: "Ulia Ushenko",
    text: "Full-stack website. Front-end developed using React, back-end built with Node.js, and MongoDB used as the database. The platform features an admin panel for a poet to upload and manage poems, with functionality for registered users to rate and comment on the poems.",
  },
  {
    id: 5,
    title: "Landing - 'Natural Forest'",
    data: "2024",
    skills: ["#react", "#css"],
    url: "https://forest-site.vercel.app/",
    foto: "./projects/natural-forest.png",
    alt: "Natural Forest",
    text: "This site is built with React. A key feature of the project is the interactive 3D main screen, where users can explore the structure more comprehensively by moving the mouse. The project also includes smooth animations, responsive design, and optimized performance for seamless user experience across different devices.",
  },
  {
    id: 6,
    title: "3D - model website",
    data: "2023",
    skills: ["#react", "#three_fiber", "#tailwind_css"],
    url: "https://3d-model-website-ten.vercel.app/",
    foto: "./projects/3-d-model.png",
    alt: "3D",
    text: "Written in React using 3D models. The main window features an interactive menu designed as a star system, where users can navigate to other pages by scrolling. The project incorporates smooth transitions, engaging animations, and dynamic content that responds to user interaction for a unique browsing experience.",
  },
  {
    id: 7,
    title: "Landing - 'Hoo bank'",
    data: "2023",
    skills: ["#react", "#tailwind_css"],
    url: "https://bank-system-weld.vercel.app/",
    foto: "./projects/hoo-bank.png",
    alt: "Hoo bank",
    text: "Written in React using Tailwind CSS. A simple landing page that highlights banking opportunities. The main advantage is the use of a new CSS library, providing a clean, modern design with highly customizable components for a responsive user experience. The site is optimized for fast load times and seamless navigation.",
  },
  {
    id: 8,
    title: "Landing - 'Hoo bank'",
    data: "2023",
    skills: ["#react", "#node"],
    url: "https://bank-system-weld.vercel.app/",
    foto: "./projects/hoo-bank.png",
    alt: "Hoo bank",
    text: "Written in React using Tailwind CSS. A simple landing page that highlights banking opportunities. The main advantage is the use of a new CSS library, providing a clean, modern design with highly customizable components for a responsive user experience. The site is optimized for fast load times and seamless navigation.",
  }
];
